### ISSUE TITLE
More then one exclude Job

### ISSUE THREAD

**Issue by xeiss** [usolved/check_usolved_veeam_backups#1]
Hello,
thanks for sharing that plugin.

I had an issue with more than one exclude job. I fixed it with changing this line
`param([string]$excluded_jobs = "")`
to this:
`param([array]$excluded_jobs = "")`

**Comment by xeiss** [comment]
project seems to be dead

**Comment by usolved** [comment]
Hm... it's weird that this solution works for you. Because you can only give strings and not arrays as an argument via Nagios. Make sure to add it this way:

`-a "jobname1,jobname2"`

In the script this string will be split at character "," and converted to an array. So I wonder why it worked for you by changing the type.
